In [29]:
from samplics.datasets import load_nhanes2
from samplics.estimation import TaylorEstimator

In [30]:
# Load Nhanes sample data
nhanes2_dict = load_nhanes2()
nhanes2 = nhanes2_dict["data"]

nhanes2.head(15)

    stratid  psuid  race  highbp  highlead   zinc  diabetes  finalwgt
0         1      1     1       0       NaN  104.0       0.0      8995
1         1      1     1       0       0.0  111.0       0.0     25964
2         1      1     3       0       NaN  102.0       0.0      8752
3         1      1     1       1       NaN  109.0       1.0      4310
4         1      1     1       0       0.0   99.0       0.0      9011
5         1      1     1       1       NaN  101.0       0.0      4310
6         1      1     1       0       0.0   93.0       0.0      3201
7         1      1     1       1       NaN   83.0       0.0     25386
8         1      1     1       0       NaN   98.0       0.0     12102
9         1      1     2       0       0.0   98.0       0.0      4312
10        1      1     1       1       NaN   92.0       0.0      4031
11        1      1     2       0       0.0   90.0       0.0      3628
12        1      1     1       0       NaN  101.0       0.0     28590
13        1      1     1       0       0.0    NaN       0.0     22754
14        1      1     2       0       1.0  123.0       0.0      7119